Repository BetterSEQTA/BetterSEQTA-Plus, pull requests merged in 2025-05, with the labels that each got.

#260 Update links.json - add more sites
  src/interface/pages/settings/shortcuts.svelte
  src/seqta/content/links.json
  src/seqta/utils/Adders/AddShortcuts.ts
Labels: enhancement

#268 Update OpenAboutPage.ts - fix grammar + adjust credits
  src/seqta/utils/Openers/OpenAboutPage.ts
Labels: documentation

#264 Subject Searching in Global Search
  src/plugins/built-in/globalSearch/src/components/SearchBar.svelte
  src/plugins/built-in/globalSearch/src/components/items/SubjectItem.svelte
  src/plugins/built-in/globalSearch/src/indexing/indexer.ts
  src/plugins/built-in/globalSearch/src/indexing/jobs.ts
  src/plugins/built-in/globalSearch/src/indexing/jobs/subjects.ts
  src/plugins/built-in/globalSearch/src/indexing/renderComponents.ts
  src/plugins/built-in/globalSearch/src/indexing/types.ts
  src/plugins/built-in/globalSearch/src/search/searchUtils.ts
Labels: enhancement, plugin

#262 add a type to bug and fr reports
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: documentation
